### ISSUE TITLE
Modules matching other modules' components with same names

### ISSUE THREAD

**Issue by opr** [One-Nexus/Cell#4]
Hi, if I have a module `container`

```scss
@include module(container) {
  background: red;
}
```
and then another module `hero`

```scss
@include module(hero) {

  @include component(background-container) {

    @include is(desktop) {
      margin: 10px auto;
    }
  }
}
```
the generated CSS:

```css
.container, [class*=container--] {
    background: red;
}
```
also affects my div named thus: `<div class="hero__background-container--desktop">`
